import sys
from PyQt5.QtWidgets import QWidget, QLabel, QApplication
from PyQt5 import QtCore

class MyLabel(QLabel):
    
    def __init__(self,*args,**kwargs):
        super(MyLabel,self).__init__(*args,**kwargs)
        
    #here we reimplement the function to respond user event    
    def mousePressEvent(self,e):
        if e.buttons() == QtCore.Qt.LeftButton:
            print(self.text()+'  generated by left button clicked.')
        if e.buttons() == QtCore.Qt.RightButton:
            print(self.text()+'  generated by right button clicked')

class MainWin(QWidget):
    
    def __init__(self):
        super().__init__()
        
        self.initUI()
        
    def initUI(self):
        
        lbl1 = MyLabel('how', self)
        lbl1.move(15, 10)

        lbl2 = MyLabel('dare', self)
        lbl2.move(35, 40)
        
        lbl3 = MyLabel('you touch me!', self)
        lbl3.move(55, 70)        
        
        self.setGeometry(300, 300, 250, 150)
        self.setWindowTitle('Absolute')    
        self.show()
        
        
if __name__ == '__main__':
    
    app = QApplication(sys.argv)
    ex = MainWin()
    sys.exit(app.exec_())
